from setuptools import setup, find_packages

setup(
    name="jcm",
    version="0.1",
    packages=find_packages(),
    package_dir={"jcm": "jcm"},
    install_requires=[
        "wandb",
        "clean-fid",
        "torchvision",
        "torch",
        "tensorflow",
        "tensorboard",
        "absl-py",
        # Keep a JAX/Flax/Haiku stack that works with CUDA 12 wheels on Python 3.9.
        "flax>=0.8.5,<0.9",
        "jax>=0.4.27,<0.5",
        "dm-haiku>=0.0.13,<0.0.14",
        "optax>=0.2.4,<0.3",
        "chex>=0.1.90,<0.2",
        "diffrax",
        "ml-collections",
        "requests",
        "scikit-image",
        "termcolor",
        "mpi4py",
        "smart-open[all]",
        "azure-identity",
        "azure-storage-blob",
        "pandas",
        "seaborn",
        "tqdm",
        "huggingface_hub",
        "h5py",
        "flaxmodels",
        "torch-fidelity",
    ],
)
